CREATE DATABASE IF NOT EXISTS finalproject_app CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS finalproject_erp CHARACTER SET utf8mb4;

CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'AppUser@123!';
CREATE USER IF NOT EXISTS 'erpuser'@'%' IDENTIFIED BY 'ErpUser@123!';

GRANT ALL PRIVILEGES ON finalproject_app.* TO 'appuser'@'%';
GRANT ALL PRIVILEGES ON finalproject_erp.* TO 'erpuser'@'%';

FLUSH PRIVILEGES;